### PR TITLE
Adding Meta Data to Header

### PR DESCRIPTION
**Pull request by ruddra**
It seems some meta data is missing from header, so when sharing a blog, it does not provide proper information in the social media posts. That is why updated the meta data in header.

### CODE REVIEW

**Comment by ruddra** [comment]
@Track3 Sorry, I didn't know about that. Updated the PR. Please have a look.

**Comment by ruddra** [comment]
Should I squash the Commits so that it does not become annoying to others? @Track3  :)

**Comment by Track3** [comment]
Don't worry, I can use Squash and merge. :)

**Comment by ruddra** [comment]
Sounds good. Thanks.

**Pull request merged**
