### PR TITLE
Added Seo Schema to Pages

### PR DESCRIPTION
**Pull request by ruddra**
Once again bothering with another PR :) . Um in PR #19 I did not include `description` meta. So including that with this PR. But I am attaching another SEO related thing which is adding schema. I have followed instruction from https://keithpblog.org/post/hugo-website-seo/. Feel free to Close the PR if you think it irrelevant.

### CODE REVIEW

**Comment by ruddra** [comment]
Maybe this will helphttps://developers.google.com/search/docs/guides/intro-structured-data

**Comment by ruddra** [comment]
Maybe we can add some flags in config to enable or disable based on user preference?

**Comment by Track3** [comment]
Maybe you are right, but I don't want this theme to be complicated. Theme's readme says:

> It's built for bloggers who want a simple and focused website.

**Comment by Track3** [comment]
#26 is merged:

Since now people can add anything in html head, this feels not so necessary, so it can be closed.

**Pull request closed without merging**
