### PR TITLE
Add code copy button to all code fields in the blog

### PR DESCRIPTION
**Pull request by Sieboldianus**
This PR adds a code copy button to all code fields in the blog.

screen_code_button

Note:  
I have a blog with lots of code fields and thought this was helpful for users who want to follow code examples. The actual code is from [Tom Spencer](https://www.fiznool.com/blog/2018/09/14/adding-click-to-copy-buttons-to-a-hugo-powered-blog/) and properly referenced. I have recompiled the scss in assets folder, so this can be used without the extended version.

### CODE REVIEW

**Comment by Sieboldianus** [comment]
Can someone explain why checks are failing? I am using this successfully in Gitlab CI and with local hugo server

**Comment by xorz57** [comment]
@Sieboldianus, Take a look at this.

```bash
12:13:54 PM: Error: failed to prune cache "assets": remove /opt/build/repo/exampleSite/resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.content: no such file or directory
```

There is a `js` folder inside another `js` folder. Is that intentional?

**Comment by Sieboldianus** [comment]
> @Sieboldianus, take a look at this.
> 
> ```shell
> 12:13:54 PM: Error: failed to prune cache "assets": remove /opt/build/repo/exampleSite/resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.content: no such file or directory
> ```
> 
> Also check this out [gohugoio/hugo#5745](https://github.com/gohugoio/hugo/issues/5745)

Thanks! I still don't get it:

* in the original branch there's a [main.js_d11fe7b62c27961c87ecd0f2490357b9.content](https://github.com/Track3/hermit/tree/master/resources/_gen/assets/js/js)
* in my [PR branch](https://github.com/Sieboldianus/hermit/tree/github-fork/resources/_gen/assets/js/js) there's the same file
* I haven't touched nor modified this file
* I've added a minified version of `code-copy.js` in the latest commit, since this was obviously missing, but the issue is still there

Netlify complains about the file `main.js_d11fe7b62c27961c87ecd0f2490357b9.content` mssing - but it [exists](https://github.com/Sieboldianus/hermit/tree/github-fork/resources/_gen/assets/js/js).

**Comment by Sieboldianus** [comment]
Well, just saw that the original branch has the same problem:
https://app.netlify.com/sites/hugo-theme-hermit/deploys

That's why [Netlify Status](https://app.netlify.com/sites/hugo-theme-hermit/deploys) shows broken sign on main page. So this seems not a problem with this PR.

**Comment by Sieboldianus** [comment]
I've tried to remove `resources` folder completely, according to [#5745](https://github.com/gohugoio/hugo/issues/5745#issuecomment-479456982), but this results in netlify error:

```
8:25:42 AM: ERROR 2019/07/24 06:25:42 error: failed to transform resource: TOCSS: failed to transform "css/style.css" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

Somehow to be expected: to build resources folder, hugo extended is needed.

I have no experience with netlify, so maybe someone else can solve this problem.

**Comment by Sieboldianus** [comment]
According [to](https://www.rockyourcode.com/deploy-hugo-extended-to-netlify-for-use-with-sass-scss), this can only be fixed by the project maintainer by switching to Xenial Image in the Netlify Dashboard.

>In your Netlify Dashboard go to "Deploy Settings" > "Build image selection" and switch to Ubuntu 16.04. The 14.04 build image doesn't support the extended Hugo 0.54 version.

There's a [closed issue](https://github.com/netlify/build-image/issues/182) on Netlify that is addressing this.

After that, remove resouces folder and let it build by Netlify hugo extended.

**Comment by xorz57** [comment]
@Sieboldianus I have no experience with web development at all. But, I think I understand the problem now!

**Comment by xorz57** [comment]
@Track3 Can you use `xenial` instead of `trusty`?

**Comment by xorz57** [comment]
@Sieboldianus I have one question. Can I turn off that `copy` button if I want to?

**Comment by Sieboldianus** [comment]
> @Track3 Can you use `xenial` instead of `trusty`?

I can't since I have no access to the repository netlify dashboard, this needs to be done by the maintainer of this repository.

> @Track3 @Sieboldianus I have one question. Can I turn off that copy button if I want to?

Simplest way to disable the feature is to override default behaviour of showing code copy button, e.g.:

```
/themes/themename/layouts/_default/baseof.html
```

… would be overridden by:
```
/layouts/_default/baseof.html
```

where you removed the following line [see](https://github.com/Track3/hermit/pull/81/commits/b01f254563c6daf2279f9275c8c06e96e2687118#diff-0c8f747dec0e7ca5148ebe8907cfc781):
```
{{ $script := resources.Get "js/code-copy.js" | minify | fingerprint -}}
```

The other way around would be to make code-copy button optional by removing the line above in the master branch.

**Comment by Track3** [comment]
Hi @Sieboldianus @xorz57 

I've switched to Ubuntu Xenial build image, but it still won't build. I think it has something to do with "hugo --gc" command, you can try to edit `netlify.toml`, remove `--gc` from the build command. I'll take a closer look into this this weekend.

**Comment by xorz57** [comment]
@Sieboldianus Is it possible to enable or disable the `copy` button from within the `config.toml` file?

**Comment by Sieboldianus** [comment]
> Hi @Sieboldianus @xorz57
> 
> I've switched to Ubuntu Xenial build image, but it still won't build. I think it has something to do with "hugo --gc" command, you can try to edit `netlify.toml`, remove `--gc` from the build command. I'll take a closer look into this this weekend.

Will look into this as soon as possible! Many thanks

**Comment by Sieboldianus** [comment]
> @Sieboldianus Is it possible to enable or disable the `copy` button from within the `config.toml` file?

I'll consider adding this option to the PR, need to look into this..

**Comment by xorz57** [comment]
@Sieboldianus Can you also make the button have 50% opacity?

**Comment by Sieboldianus** [comment]
Thanks for fixing the CI pipe!

I've added transparency to the button:
transp_ex

I think this helps to prevent code being hidden behind the button.

I've also added the option to enable/disable button in `config.toml`. The way I implemented the optional bundle.js function perhaps isn't ideal, but it works. Please feel free to change this in `baseof.html`.

Remaining things to do:

* reference Tom Spencer in README.md Acknowledgments
* add instructions to disable code-copy-button to README.md
* Merge PR :)

**Comment by Sieboldianus** [comment]
Ok, some final work on this PR:

* add compiled scss including reduced opacity for code-copy-button
* clean up all commits for PR into major ones (squash commits)

**Pull request merged**
